import fetch from "node-fetch";

// build article list
const slugList = [
  "Nhap-mon-Gundam-Nen-xem-nhu-the-nao-Phan-1-Vu-tru-Universal-Century-jTMOiUcpYP8I",
  "J4F-Vat-ly-vu-tru-va-phuong-phap-luan-qlcJDWRf8SEj",
  "Sinh-vien-chua-ra-truong-moi-ra-truong-chua-biet-dam-me-thi-chon-nghe-gi-16fEPgDtQITU",
  "xin-chao-day-la-tram-cam-nguoi-ban-than-thiet-nhat-cua-minh-HvrU2Cit1SR5",
  "6-Chien-Luoc-Giup-Ban-Cai-Thien-Ky-Nang-Doc-Tot-Hon-NgV18WGCKaTW",
  "Phan-Tich-100-Bai-Phat-Bieu-Tot-Nghiep-Day-La-4-Loi-Khuyen-Pho-Bien-Nhat-2SutvNgsi3Hi",
  "The-Shape-of-Water-2017-Truyen-co-tich-noi-ve-thoi-ky-den-toi-cua-nuoc-My-Kgzeq5CnKiGO",
  "CO-PHAI-KET-QUA-CUA-KET-HON-LA-LY-HON-yccBl6SNZcIJ",
  "5-Cach-De-Chung-To-Ban-Co-The-Lanh-Dao-Ngay-Ca-Khi-Ban-Khong-O-Vi-Tri-Lanh-Dao-3PWHgDFKXFlO",
  "ANDREW-CARNEGIE-TU-CAU-BE-NGHEO-DEN-ONG-VUA-THEP-jGltQTGmhKHT",
  "4-y-tuong-Game-hoa-ung-dung-Fintech-giup-nang-cap-trai-nghiem-nguoi-dung-cua-ban-C5FIJ4iF9NcB",
  "NGUOI-DAT-TEN-DUONG-SAI-GON-TRUOC-1975-LA-MOT-THIEN-TAI-LICH-SU-4uV3vYoBMduC",
  "Pele-Huyen-thoai-bong-da-di-len-tu-doi-ngheo-el2rrE9Ip4cv",
  "Suy-Nghi-Nhu-Elon-Musk-Voi-Tu-Duy-Nguyen-Ban-First-Principles-Thinking-YQtLKCeNGOcq",
  "GIAO-DUC-DICH-THUC-KHONG-TON-QUA-NHIEU-TIEN-gN5decd2AG0f",
  "NHUNG-GI-CAN-BIET-TRUOC-KHI-COI-Kamen-Rider-Geats-Revice-Movie-Battle-Royale-mY4GTyoka1Ox",
  "CON-DONG-TINH-U-ME-BIET-Bx1oQLaDbRqb",
  "CHUYEN-VE-CAY-LUA-VA-KIM-CUONG-mmHb9NFTzuKX",
  "World-Cup-2022-Bua-tiec-tren-hinh-the-phu-nu-7QvQASaAOH1R",
  "SU-THAT-VE-THOI-MIEN-HOI-QUY-TIEN-KIEP-VA-HIEN-TUONG-DAU-THAI-jIZPLXtwONAz",
  "Ao-tuong-ca-nhan-va-cai-toi-cua-GenZ-MuJegZqjZaHH",
  "Biet-minh-khong-muon-gi-urIDGsZpQGdq",
  "Se-ra-sao-neu-Ethereum-nga-ngua-ttEW9LbnOjop",
  "Tuoi-20-rat-cliche-wc213V1gpeKW",
  "DO-KY-LA-MOT-LOAI-TAM-BENH-sNkOqLux0LYG",
  "Critical-Race-Theory-and-critical-analysis-of-Vietnamese-Americans-relations-An-extravaganza-rBFrUvddIQDt",
  "Mot-trong-nhung-phat-minh-tuyet-voi-nhat-cua-nhan-loai-86mrO6FvnxLM",
  "Het-viec-chu-khong-het-gio-van-vo-va-van-hoa-lam-viec-p6Xcmo9UpgmP",
  "Toi-dang-mac-ket-giua-hai-cau-noi-Hay-tiet-kiem-khi-con-tre-va-Ta-chi-song-mot-lan-tren-doi-H0GsGR0rnb4L",
  "Boi-thuc-thong-diep-nham-tren-mang-xa-hoi-va-hau-qua-tam-ly-no-mang-lai-bCfevculERkF",
  "Phan-Thiet-Phan-Thiet-XpTEHHf46pES",
  "THANG-12-KHOI-DONG-LAI-SAU-MOT-NAM-DANG-QUEN-v0qle75Ox0f9",
  "Thong-dong-ma-ban-QPnSUZkHXhAN",
  "Tinh-duc-chuyen-te-nhi-hay-huych-toet-73JRRLV5AdTm",
  "Cai-gia-that-su-cua-viec-di-chuyen-I2VCxwkSbMY5",
  "Xich-lo-1995-Va-khi-tan-vo-v9lWycL8vonL",
  "Book-review-Nhung-tu-nhan-cua-dia-ly-Tim-Marshall-KlYAmrlszjvS",
  "Con-duong-dan-toi-cuoc-song-thinh-vuong-i67PlGVZhFQz",
  "Lady-Gaga-truoc-Lady-Gaga-zlstu1Gzpdkl",
  "Mot-goc-nhin-khac-ve-Decision-To-Leave-o5F0qlmS81cu",
  "DAU-KHOP-GOI-O-NGUOI-TRE-XbxytAngnJ60",
  "Minh-rat-nho-Viet-Nam-QWZpOOLmsVDJ",
  "Tinh-yeu-La-gi-the-nhi-YoCe2bK0J7Zj",
  "Toi-da-do-ki-voi-ban-than-cua-minh-jraMP3XugkDZ",
  "Review-Sach-Tu-truyen-Osho-1FKnZmjYn31I",
  "Shopee-gan-day-khac-gi-Shopee-cua-nhung-nam-truoc-chKKtV3XyTxC",
  "Yeu-de-trai-nghiem-la-sai-FCstNOlg6mGA",
  "Hue-va-co-gai-tuoi-20-Ckd19UKhoZQf",
  "Truyen-tranh-va-tuoi-tho-ycpb59OpEQSe",
  "1-BAI-HOC-1000-ICH-LOI-TVdWK7xSsU0e",
  "Khong-phai-cu-Game-hoa-la-nguoi-ta-thich-choi-tJfC36bez8Rl",
  "Cau-chuyen-ve-crypto-duy-nhat-ban-can-P16-CpznaSDTcnVF",
  "Cau-chuyen-ve-crypto-duy-nhat-ban-can-P26-0xxZDRJ9hvl3",
  "Cau-chuyen-ve-crypto-duy-nhat-ban-can-P66-phYklPXRGhhD",
  "Cau-chuyen-ve-crypto-duy-nhat-ban-can-P56-WFcscdPLJHE8",
  "Cau-chuyen-ve-crypto-duy-nhat-ban-can-P46-hiCVcWnzIlFP",
  "Xem-gi-cho-mua-Giang-Sinh-them-am-ap-gEjnFkLfVKpy",
  "Con-gai-co-thich-lam-con-gai-khong-cMxIp2wt18MI",
  "Co-don-lam-nguoi-ta-so-hai-con-co-doc-khien-nguoi-ta-manh-me-chP3BNvDjbcu",
  "Cau-chuyen-ve-crypto-duy-nhat-ban-can-P36-VyfkqUpN68qy",
  "Tap-1-Thuc-tinh-9EMopOYO64bq",
  "Su-xung-dot-the-he-dao-dien-thu-5-va-thu-6-cua-Trung-Quoc-qua-nhung-tac-pham-cua-ho-voi-thoi-dai-azIIsx9b29cx",
  "Vi-du-nhan-qua-va-nghiep-HdK4JpOoLvrl",
  "SUY-THOAI-KINH-TE-VA-NHUNG-BAI-HOC-MA-TOI-RUT-RA-oC9qpReb8g1O",
  "Trai-tim-cua-thuyen-truong-Davy-Jones-kQmNUwGddTyN",
  "Anh-trong-nhu-nao-y-nhi-hvaEgssm4keH",
  "Toi-tu-hoc-Bai-3-Quan-ly-du-lieu-dBtfw21vtSZQ",
  "Viet-cho-thoi-tuoi-tre-cua-toi-4iL0pRaPHLgN",
  "4-dau-hieu-cho-thay-ban-mac-hoi-chung-nguoi-tot-hyenlRCixLUa",
  "Hanh-trinh-quyen-luc-cua-Giang-Trach-Dan-VTXNhQZpLUTc",
  "J4F-Nen-dau-tu-gi-voi-100-trieu-MlnsVPw7LG8w",
  "Nhung-dieu-lam-tuoi-20-ca-doi-se-nhan-ha-dcJqa90cBw20",
  "Tu-Duy-Dao-Duc-Cho-Ban-Tre-Nhu-the-nao-la-mot-ke-co-dao-duc-va-vo-dao-duc-RIXk8L21Jyvy",
  "Yeu-cau-loai-bo-diem-so-trong-giao-duc-la-mot-doi-hoi-phi-ly-MeWKXYzhXt8y",
  "Khi-Ta-Tan-Thanh-Tro-Tan-Ruc-Ro-~-rOsYrepsa7ki",
  "NHAN-THUC-VE-NHAN-QUA-VA-NGHIEP-KdDLg9YqAuqu",
  "Bao-lau-roi-ban-chua-duoc-khoc-W1Tjz3QS30v0",
  "Xung-dot-kich-trong-tac-pham-Vua-Lear-cua-William-Shakespeare-eaRyMYLpbbpQ",
  "The-Punisher-Ga-tu-hinh-cua-thanh-pho-New-York-m1AuMdLjYCUH",
  "QUAY-ROI-TINH-DUC-O-NU-GIOI-CAU-CHUYEN-TIEU-LAM-p2wDnhjsYYus",
  "Tri-tue-co-nhan-Khoe-khoang-tai-gioi-la-tu-ruoc-hoa-vao-than-a73W5itb4Zhl",
  "CHAN-THUONG-TAM-LY-LA-MOT-PHAN-TAT-YEU-CUA-CUOC-SONG-hzS8RE9PULFz",
  "Khi-thoi-gian-cho-uoc-mo-khong-con-nhieu-9SadosieiGdx",
  "Cac-moi-quan-he-than-thiet-cang-gan-gui-thi-cang-phai-ton-trong-nhung-gioi-han-rieng-brofKrrWCuhq",
  "8-Cach-so-cuu-cam-xuc-khi-tre-gap-tai-nan-EZnM0JvTxgqs",
  "Lady-Bird-2017-Hay-bay-that-cao-that-xa-vi-ta-luon-co-gia-dinh-o-phia-sau-4djMCwwCReCi",
  "Hoc-duoc-gi-qua-10-nam-bon-ba-xu-nguoi-Phan-2-Di-de-truong-thanh-g5LJ8oXSDVs1",
  "Muon-chuyen-tinh-yeu-ban-chuyen-tinh-yeu-YyvHYdxjmtEj",
  "Hoang-tuong-tu-duy-nuoc-doi-va-bi-kich-cua-mot-nen-Triet-hoc-da-chet-YpTvOlbtCIaW",
  "Cu-viet-thoi-PGJLiykMdnO2",
  "Co-phieu-cua-ban-sao-roi-trong-nam-2022-Dv9A8ABkhXwe",
  "Toi-khong-muon-co-to-ra-ve-minh-la-nguoi-co-ich-nua-9m7Go7meAMVK",
  "Binh-dang-nhung-lai-khac-biet-OdDqh7twC1qP",
  "Dinh-nghia-Tokusatsu-va-lich-su-phat-trien-iZoLKMuiW0f4",
  "CHAT-LUONG-NGHE-LOM-VxomoS8eygTf",
  "Lam-nguoi-canh-gioi-cao-nhat-ky-thuc-la-2-chu-gia-kho-ZrPXnDJlN6kL",
  "Su-tien-hoa-cua-cac-chuong-trinh-khach-hang-than-thiet-Loyalty-Program-rijdnv9hVira",
  "12-dau-hieu-khi-ban-di-tren-con-duong-thien-IpgTzZlPDf2x",
  "Ban-luan-vong-dau-World-Cup-2022-vua-qua-nhieu-su-trung-hop-den-ky-la-jml3xb7yhrMu",
  "Tai-sao-toi-ung-ho-Vinfast-YpvAVIoOgm9E",
  "Doi-Binh-Dang-P2-LPCOBASa5Tk2",
  "Bai-hoc-ve-Anh-hung-cuu-the-va-ke-yeu-trong-Dune-Va-nhieu-thu-khac-wNNFAufh2QVZ",
  "Tulpa-Nguoi-ban-tuong-tuong-vo-hinh-Phan-I-Tong-quan-70SwIdtyQdBS",
  "Tap-trung-vao-chuyen-mon-DI-VE-SINH-H0uTwzcjY9vJ",
  "Bat-cap-va-cai-nhin-sau-hon-ve-thap-nhu-cau-Maslow-9h4UX0RO1jYA",
  "MICHAEL-E-PORTER-VA-LI-THUYET-VE-CANH-TRANH-qaVnZeNYZKtT",
  "Review-Sach-Kim-chi-nam-cua-hoc-sinh-hamgY8UTZ25z",
  "Nhu-Cau-Duoc-Tu-Do-Co-The-Manh-Den-Nhuong-Nao-AqPvebwq0uHt",
  "Ban-da-hoan-thanh-muc-tieu-hom-nay-chua-Gn5OKU9Mbm83",
  "DRX-tan-ra-Suc-manh-tinh-ban-hay-tien-quan-trong-hon-bGvvYsOUdAIE",
  "Chia-se-Chuyen-tam-bang-va-viec-lam-7FRLKWvHYhhg",
  "Sao-con-khong-the-nhu-nguoi-binh-thuong-y82I7OxxMPbz",
  "Ba-vi-du-ve-cach-xay-dung-Muc-tieu-trong-ung-dung-Game-hoa-wokVNNq7wTwU",
  "Nhung-thu-ngu-xuan-tren-internet-p1-Mot-dang-content-so-keo-suc-manh-nhan-vat-ngu-xuan-VY5rvQ4SGfQJ",
  "Nhung-cuoc-khung-hoang-trong-qua-khu-cua-Fed-Ngan-hang-Trung-uong-Hoa-Ky-P1-sShMOVnMrV7Y",
  "Cung-sinh-vien-dai-hoc-Thuong-Mai-tren-hanh-trinh-nghe-nghiep-VJ9OkkChxz4x",
  "Yeu-nhau-nhu-nguoi-hay-nhu-loai-cam-thu-NE2ta56uaCVc",
  "Nguyen-Tuan-va-tap-doan-Hoang-Tich-Chu-Xs4xuRGoxz2h",
  "3-CUON-SACH-GOI-DAU-GIUONG-NEU-BAN-MUON-THANH-THAO-SQL-14RumkINJWr1",
  "Trai-nghiem-2-tuan-lam-tinh-nguyen-vien-quoc-te-tai-nuoc-Cong-hoa-Dan-chu-Nhan-Dan-Lao-co-gi-vui-Phan-1-4rETBbwcg2no",
  "HYBS-SUC-MANH-TINH-BAN-VA-SU-RA-DOI-CUA-ALBUM-MAKING-STEAK-0V5bSv31hmyG",
  "Pixar-va-nhung-thong-diep-mang-tinh-thoi-dai-FaJUOdzZgL7U",
  "Duoc-va-mat-khi-dung-May-Doc-Sach-dRgRR2t1T98f",
  "Thu-nhin-vao-ban-chat-cua-su-lua-doi-cap-ke-XB1q2kpmMwAr",
  "NGHIN-TRUNG-XA-CACH-cuMGPv6kTT7x",
  "Toi-tu-hoc-Bai-2-Data-Type-qua-tao-cua-mu-phu-thuy-bk8n0VX0tNHW",
  "Dich-bua-Muoi-nam-lam-lap-trinh-cua-toi-Loi-Quan-mgHGcnh4N8i9",
  "Khi-ap-luc-hoa-huu-hinh-Geto-Suguru-hZ9vEyAOEGYc",
  "Dao-dien-doat-giai-Oscar-Asghar-Farhadi-da-thuc-su-danh-cap-y-tuong-tu-nguoi-khac-phan-cuoi-5vlr9gkY63Pg",
  "Dao-dien-doat-giai-Oscar-Asghar-Farhadi-da-thuc-su-danh-cap-y-tuong-tu-nguoi-khac-phan-5-gSUWoaFZ1AUx",
  "Mo-khoa-Thuong-Mai-Dien-Tu-Viet-Nam-bi-kip-tu-zero-toi-trieu-do-cua-nhung-ai-da-dang-va-se-tro-thanh-selle-KkwQZmlKFe1Y",
  "Vinfast-Dang-Bi-Chi-Trich-Qua-Muc-Can-Thiet-rNj7yUWYcQan",
  "Suy-thoai-kinh-te-thi-truong-downtrend-huong-di-nao-cho-doanh-nghiep-tren-TMDT-e2yxvhQdQXjw",
  "Toi-tu-hoc-Bai-1-Ky-nang-tin-hoc-van-phong-7TqOi1yqSVwz",
  "Phim-Weak-Hero-Class-1-2011-Khi-truong-hoc-khong-chi-day-hoc-vo6abH0atIWJ",
  "Under-the-Queens-Umbrella-Ep09-Giac-mo-cua-me-giac-mo-cua-con-1dZ9vxHsRHod",
  "Giai-ma-suc-manh-dia-ly-cua-Thanh-Hoa-Q8UOm8YzQvUm",
  "Tai-sao-Trung-Quoc-luon-muon-giu-chinh-sach-Zero-COVID-OejBoxkz018Q",
  "SACH-GIAY-HAY-KINDLE-MP73OdWKAkui",
  "Bon-buoc-de-Game-hoa-loi-song-cua-ban-xWQlK2MRSHbg",
  "BO-MINH-NGOC-CUC-Uf8vlsnKc0o2",
  "Nhung-bai-hoc-va-triet-ly-sau-sac-trong-Kungfu-Panda-1-Phan-6-cuoi-TmgQNnFyshh3",
  "XE-DIEN-and-XE-PIN-NHIEN-LIEU-4wQ9YCAvOrkt",
  "Giao-duc-cong-dan-ve-chinh-tri-Hoc-sinh-hoc-duoc-gi-gox1ekGy1i48",
  "CHUNG-TA-KHONG-THE-NGOI-IM-CHO-THAY-DOI-TIgDOq00n6IF",
  "Drama-Tiktoker-trieu-views-va-vai-suy-nghi-ve-chuyen-giau-ngheo-H94pUGOWCu4e",
  "Lieu-thuoc-an-ui-va-chua-lanh-cho-tre-truoc-chan-thuong-tam-ly-6rHXzJQUbcGP",
  "Cach-lam-ban-voi-stress-trong-hoc-tap-2BPD98CeBJnJ",
  "LOL-Tom-tat-thi-truong-chuyen-nhuong-LCK-mua-xuan-2023-gJxRRhcXem9Q",
  "Dao-dien-doat-giai-Oscar-Asghar-Farhadi-da-thuc-su-danh-cap-y-tuong-tu-nguoi-khac-phan-4-2YRMqC7CvI3q",
  "Tan-man-Chuyen-chon-vo-WSE2iRTvjSHz",
  "NONG-CUNG-WORLD-CUP-LA-TAN-CUNG-LICH-SU-rGv2MwjkzmDo",
  "Dao-dien-doat-giai-Oscar-Asghar-Farhadi-da-thuc-su-danh-cap-y-tuong-tu-nguoi-khac-phan-3-2l9Hb0CN9YaR",
  "Bat-dau-moi-thu-don-gian-thoi-nZZEXy0IcS2U",
  "CON-NGUOI-VA-DOI-SONG-GIA-DINH-ugARS8Hfct8K",
  "Mot-dan-toc-dao-lon-nhan-qua-gLl1PhqxAH2M",
  "Phim-su-Viet-ai-moi-la-nguoi-dang-coi-thuong-lich-su-khan-gia-hay-nha-lam-phim-qrknd007MASj",
  "Tram-ke-tiep-cua-to-la-gi-day-18jV0Ge8rk7R",
  "MON-MOI-CHO-MOT-CON-SONG-HOI-3PDMKT2L8LQU",
  "Medal-of-Death-Chuong-7-TRIET-BQiTZusViLdp",
  "Gen-Z-Mot-the-he-nhay-cam-Mot-the-he-de-vo-Mot-the-he-luon-khoc-than-U7syi1ErUzTX",
  "Hoc-duoc-gi-qua-10-nam-bon-ba-xu-nguoi-Phan-1-Ve-tieng-Anh-A5HU8WgrMV1L",
  "De-gap-year-khong-tro-thanh-mot-lua-chon-vo-ich-uZGPHDNhOQL7",
  "Overthinking-suy-nghi-nhieu-qua-thi-lam-gi-0rObRlVad455",
  "7-toi-loi-trong-Kinh-Thanh-duoi-goc-nhin-cua-Chu-Nghia-Khac-Ky-JbS5g6GFEgYR",
  "Die-Mannschaft-2022-Xac-xe-tang-khong-hon-a8EKtBoFJR5r",
  "Vu-tru-hinh-xuyen-Toroidal-oJvdfMrsdESE",
  "Nhung-bai-hoc-va-triet-ly-sau-sac-trong-Kungfu-Panda-1-Phan-5-0HVZIsUxPqMD",
  "Jason-David-Frank-Nguoi-mang-hy-vong-toi-toan-nhan-loai-S3IB9wqbfIJp",
  "DU-HANH-DUOI-ANH-TRANG-reOBa3yJ4aWK",
  "NGHE-TU-DO-CUNG-KHO-E1z5z7WzpxEu",
  "Nhung-bai-hoc-va-triet-ly-sau-sac-trong-Kungfu-Panda-1-Phan-4-DWsXTav5DxY4",
  "Is-it-okay-not-to-be-okay-LEYPGwZdSgvO",
  "HAY-DAT-CON-LUOI-TRUOC-RIA-VUC-THAM-BVMk3k5uclTW",
  "Chu-nghia-dan-toc-am-thuc-Su-tro-treu-cua-ngan-ngu-Ban-la-cai-ma-ban-an-5QTDOkESZmgq",
  "Dieu-gi-dang-cho-doi-Vladimir-Putin-DwSBigT2oM3L",
  "Chung-ta-da-hieu-het-ve-bao-luc-hoc-duong-If484h4gtKh1",
  "Di-chua-cau-gi-fywkTYCYJz7G",
  "Review-Phim-Duong-ve-nha-The-Way-Home-luTi8uUIsnEA",
  "DAM-CUOI-NGUOI-YEU-CU-XGuL8I5lwd0c",
  "Its-All-Good-dE72OmJOP25F",
  "Tuoi-nao-doc-sach-gi-jyJ3jx0DweVp",
  "TOI-VA-TRAP-BOY-2-CUOC-GOI-LUC-NUA-DEM-HIEU-UNG-TAM-LY-STOCKHOLM-dEXsrLHFVU9u",
  "Dao-dien-doat-giai-Oscar-Asghar-Farhadi-co-thuc-su-danh-cap-y-tuong-tu-nguoi-khac-phan-2-Gxvkym3e3b27",
  "Nhung-bai-hoc-va-triet-ly-sau-sac-trong-Kungfu-Panda-1-Phan-ba-9hemREKEGSrn",
  "One-Dreamer-da-day-nguoi-choi-lap-trinh-nhu-the-nao-S4X0hmEhfSMD",
  "Lu-cuu-chung-ta-va-drama-crypto-lon-nhat-cua-2022-834vqfU1eUC0",
  "GIA-THUYET-GAME-OF-THRONES-Ai-da-day-nguoi-Valyria-cach-dieu-khien-rong-YymNnrHqlBJj",
  "Review-Sach-Nhung-buoc-don-gian-den-uoc-mo-kQHyF7TLWgaU",
  "Chia-se-Chuyen-nguoi-thay-HOAe1xHAk5JU",
  "Dao-dien-doat-giai-Oscar-Asghar-Farhadi-co-thuc-su-danh-cap-y-tuong-tu-nguoi-khac-phan-1-ZipTQOjpy1AJ",
  "Tot-nghiep-tre-mot-nam-thi-co-gi-vui-k8TMzd45HVhx",
  "Hanh-dong-the-hien-dieu-ban-tin-8MbZqqK3f4ZL",
  "Mot-so-nguoi-thay-noi-tieng-trong-lich-su-Viet-Nam-YU7tVckUUV6q",
  "Kamen-Rider-W-Rider-dam-chat-Showa-cua-ky-nguyen-Heisei-xe0J5JpGvRuK",
  "THE-CO-DEPENDENCY-MYTH-Hay-nhung-nham-tuong-ve-le-thuoc-cam-xuc-PXkLdPWOozho",
  "Da-tu-lau-minh-chang-con-mong-doi-nguoi-yeu-ga-lang-nua-2IZ4DJbKu1vf",
  "Toi-tieu-cuc-hay-tich-cuc-WoTD8ra4bzJp",
  "Ronaldo-di-san-va-nhung-vet-ran-gill5gQxsSWR",
  "Nhung-triet-ly-va-bai-hoc-sau-sac-trong-Kungfu-Panda-1-phan-2-QCuwMlmH3QT0",
  "Nhung-bai-hoc-va-triet-ly-sau-sac-trong-Kungfu-Panda-1-qHJsh6Pwdgot",
  "mot-dieu-kho-hieu-tren-YouTube-G2hTQlw6F85g",
  "Doi-tra-va-kho-dau-ZdSiGzx5qWM2",
  "Cuoc-doi-Spinoza-truoc-nam-24-tuoi-ogKU3pGKUn1M",
  "Chuyen-ke-mot-ke-phai-gio-zfAsvSorbRea",
  "Lam-the-nao-de-tu-hoc-hieu-qua-phan-3-j5AcjQTTXFer",
  "Tai-sao-con-nguoi-say-me-va-suu-tam-Phan-1-E7nCxYNMg2Oz",
  "BIEU-TUONG-NGUOI-ME-TRONG-GAME-OF-THRONES-LaMbL5s9rLpc",
  "Khong-khach-quan-ma-cung-chang-chu-quan-aXIQTPwDwoHD",
  "Goc-nhin-tu-Chu-nghia-khac-ky-trong-cai-ket-cua-20-Century-Girl-dD87UU0SWOSc",
  "Chuyen-toi-tap-yeu-con-muoi-dHOpY77NHpkO",
  "Dich-ASSASSINS-CREEDr-VALHALLA-MOT-BAN-CAP-NHAT-HAU-PHAT-HANH-yyaVPxM2g2Ac",
  "Nhung-tro-he-cua-giao-duc-nhan-ngay-Nha-giao-tqMdxeJHurhA",
  "Ban-Co-Biet-Tra-On-Chua-lOusKy9GtwuF",
  "Ba-bi-mat-giup-cuoc-song-cua-ban-tro-nen-don-gian-hon-8uBIYsgOKAPQ",
  "CR7-Ai-da-phan-boi-toi-va-sac-mau-cua-ke-phan-dien-vi-dai-BkaAcOJgCUPE",
  "NHUNG-DUC-TINH-CUA-NGUOI-LANH-DAO-TRI-TUE-Yqli5m48guqN",
  "Loi-ich-thuc-su-cua-Am-Nhac-nghe-dung-nhac-de-co-cuoc-song-tuoi-dep-hon-b0ThZF6Xq4B4",
  "Ban-chi-dang-dau-tu-Rip-to-tren-nhung-cau-chuyen-O1MYuG1d4hPL",
  "Truyen-Dung-Khi-va-nhung-dieu-co-the-ban-chua-biet-6oXY0BvpUTeQ",
  "Nhung-phan-mo-to-06F5HsjLu79T",
  "Tu-bieu-tuong-Yin-Yang-noi-chuyen-tinh-yeu-V1x7oz6fQnOg",
  "VI-SAO-TU-DUY-PHAN-BIEN-LAI-KHO-MOT-VI-DU-TU-VIEC-HOC-NGON-NGU-NvpH9tnAq3vx",
  "Cung-la-dao-ly-nhung-no-la-lam-Hn31S7H99nLD",
  "Nha-nghien-cuu-o-dau-trong-nghien-cuu-cua-chinh-minh-8MRz8vGoxQ9W",
  "Hieu-ung-Brita-va-cau-chuyen-tu-hoc-OTl8wfCQpypm",
  "LAM-GI-KHI-BI-BOI-THUC-THONG-TIN-KCU9xv6Zil4i",
  "FTX-and-Alameda-Research-mot-loi-noi-doi-hang-trieu-nguoi-boc-hoi-tai-san-GkEsQLrFEj5j",
  "Miroslav-Klose-Huyen-thoai-den-tu-su-Gian-Don-JZ3HCdRcxjq1",
  "Nhan-dinh-ve-Joker-ban-chat-toi-cua-ga-he-toi-pham-Phan-1-bfc830szD5f7",
  "Nhung-gi-ban-can-biet-ve-Balerion-Con-rong-huyen-thoai-cua-nha-Targaryen-jNujozes1xJI",
  "Chu-nghia-Khac-ky-da-la-nguon-cam-hung-cho-nhung-nha-lanh-dao-tro-nen-dung-cam-nhu-the-nao-7AkKGzGN8Uq3",
  "KY-LUC-WORLD-CUP-NAM-VI-DAI-NHAT-MOI-THOI-DAI-zyiSbgnw3fPf",
  "Su-that-dang-sau-nhung-ung-dung-the-duc-Game-hoa-Can-than-khong-mat-dong-luc-ze306BzUmdwC",
  "10-TAP-THE-XUAT-SAC-NHAT-MOI-THOI-DAI-TAI-WORLD-CUP-MXs1GJueY1Y2",
  "Nguy-bien-tich-cuc-hoa-tu-sach-va-mot-vai-van-de-cua-tu-tuong-tich-cuc-hoa-MO5ymDWGjvMb",
  "BLACK-PANTHER-WAKANDA-FOREVER-HOI-KET-KHONG-HOAN-HAO-CUA-PHASE-4-r48teBfivFYO",
  "Review-phim-Hop-dong-tinh-yeu-bo-phim-banh-cuon-tu-nhung-tap-dau-nhung-roi-heo-dan-ve-sau-axgvWGI5TZKC",
  "Ky-1-Khieu-vu-giua-bay-suc-vat-hay-la-nhat-ky-ke-dien-16-GgZrhPN3VDOq",
  "Tham-Du-co-don-gian-la-nghien-vo1vkCDp6ID2",
  "CHUAN-BI-CHO-MOT-CUOC-CHIA-TAY-FrahmzOI7K2X",
  "Tang-nghia-an-trong-The-Ones-Who-Walk-Away-from-Omelas-cua-Ursula-K-Le-Guin-UfIJhRUEujhm",
  "Mat-trai-cua-luat-hap-dan-8fyCbnM4zghl",
  "REVIEW-NEW-GETTER-ROBO-2004-Gam-len-di-hoi-Long-chien-si-4TKEgITPSTn4",
  "Layoff-O-Viet-Nam-thi-sao-P23-oS2ED1iWzZ4c",
  "Nhay-tango-mot-minh-Hay-chuyen-yeu-va-chuyen-chia-tay-06PFw1GKlzv6",
  "Chia-khoa-vang-cua-hon-nhan-mang-ten-Intimacy-g4BsL3sT4ZQw",
  "Mot-so-dieu-cho-lap-trinh-vien-ngay-dau-di-lam-cong-ty-moi-E34DPIZKqBt2",
  "Co-hoc-mot-cach-vo-hoc-AK1grOmoweBK",
  "Netflix-Trust-No-One-The-Hunt-for-the-Crypto-King-va-bai-hoc-tu-vu-sap-cua-san-FTX-uhTKDKWkW8p4",
  "Benh-man-tinh-overthinking-den-gay-gat-khi-bien-luan-Z4HelygkaUbN",
  "Lam-tinh-voi-chu-aglIdQpAv3r5",
  "DOC-QUYEN-VA-DOC-QUYEN-NHOM-u8wvQ46A6W3p",
  "Buoi-Podcast-ngan-ngui-giua-toi-voi-ong-dai-gia-Anh-re-E5nl2nbCSudv",
  "EMINEM-VA-VIEN-NGOC-BI-CHON-VUI-MANG-TEN-INFINITE-KKUwJZ5ADxCD",
  "Phan-thang-di-dao-vang-o-Spiderum-Phan-1-Dao-sBctGTESnY6L",
  "Tam-ly-nao-khien-ban-khong-dam-dau-tu-Chien-luoc-dau-tu-an-chac-mac-ben-trong-mua-giong-bao-OEuDpnGNaCXf",
  "Vai-ghi-chu-sau-khi-doc-Phap-su-va-nha-tien-tri-Ve-bien-doi-khi-hau-va-tuong-lai-cua-con-nguoi-fhOR4VFqiC7E",
  "That-bai-kho-khan-toi-tung-gap-phai-trong-viet-lach-bBOIbMndJ0aF",
  "Yeu-cay-va-cau-chuyen-ve-long-tin-JYsaSdcibQmg",
  "REVIEW-SACH-TU-THAM-THAM-LANG-QUEN-t9kwG960UGNH",
  "Lich-su-la-cai-dech-gi-77IupJniZhZ0",
  "Nghe-thuat-cua-su-luoi-bieng-ZTDEMvxWCU0Y",
  "Dan-ong-truy-cau-su-ngay-tho-la-de-tan-huong-khoai-cam-huy-diet-no-aJbKShjclw7o",
  "KAMEN-RIDER-BLACK-SUN-Anh-Mat-troi-cua-man-Dem-toi-77YdhszXtv4r",
  "Lam-the-nao-de-tu-hoc-hieu-qua-phan-2-dmuuquRlCbil",
  "Review-The-Ones-Who-Walk-Away-from-Omelas-cua-Ursula-K-Le-Guin-mot-cau-chuyen-khong-the-review-SwRu9GulEJeO",
  "Nokia-vi-dau-den-noi-We9LGBrjvPYT",
  "Beginners-Mindset-yFS3GrFhoIzX",
  "HANH-DONG-Hanh-trinh-tao-nen-nhung-thay-doi-tich-cuc-sZVM30JaVvqi",
  "Suy-nghi-trong-luc-leo-dinh-Nhiu-Co-San-2965m-tleHmQyvdlwU",
  "Hoc-ve-feedback-tu-chuyen-hoi-nach-BMCVVtCL1ytS",
  "Muon-song-ban-linh-doc-gi-cho-hay-U5NPS3sDt3Y5",
  "Hay-tranh-luan-nhu-Tornad-It-nhat-cung-phai-lam-duoc-mot-phan-nao-do-nhu-anh-ta-da-lam-mkFBsKsGN8xL",
  "Review-Sach-Dep-Va-Buon-EUftvdnvYQKS",
  "XAY-DUNG-DONG-LUC-DE-HOC-NGOAI-NGU-HIEU-QUA-BAN-DA-BIET-CACH-CHUA-xynY1wyInJ7O",
  "Noi-ve-liem-si-XGH7brrEVwVb",
  "Review-Books-Vai-cuon-sach-ve-nhung-ac-nhan-kinh-dien-xN2MlPzcV7ae",
  "Bo-Rung-dai-chien-Ngua-Hoang-Ferruccio-Lamborghini-doi-trong-hoan-hao-cua-Enzo-Ferrari-WuwOig9K6yOp",
  "Nhung-gi-ban-can-biet-ve-Vhagar-con-rong-lon-nhat-cua-nha-Targaryen-trong-House-of-the-Dragon-NNF0BfbjzzTy",
];
const buildArticle = (post) => {
  return {
    title: post.title,
    description: post.description,
    tagList: post.tags.map((tag) => tag.name),
    blocks: post.body.blocks.map((block) => ({
      type: block.type,
      data: {
        alignment: block.data?.alignment,
        text: block.data?.text,
        caption: block.data?.caption,
        file: {
          url: block.data?.file?.url,
          info: {
            width: block.data?.file?.info?.width,
            height: block.data?.file?.info?.height,
          },
        },
      },
    })),
  };
};

const fetchPost = async (slug) => {
  const response = (
    await fetch(`https://spiderum.com/api/v1/post/${slug}`)
  ).json();
  return response;
};

const final = async () => {
  const list = [];

  for (const slug of slugList) {
    const { post } = await fetchPost(slug);
    const article = buildArticle(post);
    list.push(article);
  }

  console.log({ list });
  return list;
};

final();
